#!/bin/sh
exec 2>&1
sv once bondd
sleep 1
ip link set WIFI down
ip link set dev bond0 down
ip addr add 192.168.1.xx/xx dev bond0
ip link set dev bond0 address xx:xx:xx:xx:xx:xx
ip link set ETH0 down
ip link set ETH1 down
ip link set ETH0 master bond0
ip link set ETH1 master bond0
ip link set dev bond0 up
sleep 1