#!/bin/sh

case "${1-}" in
    'pre')
        echo suspend > /proc/driver/nvidia/suspend
        ;;
    'post')
        echo resume > /proc/driver/nvidia/suspend
        ;;
    *)
        exit 1
        ;;
esac

